### ISSUE TITLE
error updating ucsb-izc

### ISSUE THREAD

**Issue by seltmann** [ParasiteTracker/tpt-reporting#13]
I am able to update all of the datasets except ucsb-izc. I updated to elton 0.9.5 and had no problem with these datasets:
globalbioticinteractions/fmnh
globalbioticinteractions/mpm
globalbioticinteractions/ummzi
globalbioticinteractions/inhs-insects
globalbioticinteractions/vectorbase
globalbioticinteractions/vertnet
globalbioticinteractions/scan

any clues?

Katjas-MacBook-Pro:globalbioticinteractions katjaseltmann$ elton update globalbioticinteractions/ucsb-izc >log-04-26-ucsb-izc.txt
updating [globalbioticinteractions/ucsb-izc]... failed to handle namespace [globalbioticinteractions/ucsb-izc]
org.globalbioticinteractions.dataset.DatasetFinderException: failed to configure dataset in namespace [globalbioticinteractions/ucsb-izc] with archiveURI [https://github.com/globalbioticinteractions/ucsb-izc/archive/6438c9708585c5ac3ee3296d09deed822da4ff37.zip] and citation [Accessed on 2020-04-27T04:02:22.053Z via <https://github.com/globalbioticinteractions/ucsb-izc/archive/6438c9708585c5ac3ee3296d09deed822da4ff37.zip>.]
	at org.globalbioticinteractions.dataset.DatasetFactory.datasetFor(DatasetFactory.java:51)
	at org.globalbioticinteractions.elton.cmd.CmdUpdate.lambda$run$0(CmdUpdate.java:65)
	at org.globalbioticinteractions.elton.cmd.CmdUtil.handleNamespaces(CmdUtil.java:47)
	at org.globalbioticinteractions.elton.cmd.CmdUpdate.run(CmdUpdate.java:80)
	at org.globalbioticinteractions.elton.cmd.CmdLine.run(CmdLine.java:18)
	at org.globalbioticinteractions.elton.cmd.CmdLine.run(CmdLine.java:27)
	at org.globalbioticinteractions.elton.Elton.main(Elton.java:20)
Caused by: org.globalbioticinteractions.dataset.DatasetFinderException: failed to find configuration
	at org.globalbioticinteractions.dataset.DatasetFactory.configDataset(DatasetFactory.java:77)
	at org.globalbioticinteractions.dataset.DatasetFactory.datasetFor(DatasetFactory.java:46)
	... 6 more

**Comment by seltmann** [comment]
Also, how do you update all of the datasets in the datasets.tsv, rather than one at a time?

**Comment by seltmann** [comment]
@jhpoelen elton update globalbioticinteractions/ucsb-izc is giving me an error. The rest of the datasets I can update with no issue

globalbioticinteractions/fmnh
globalbioticinteractions/mpm
globalbioticinteractions/ummzi
globalbioticinteractions/inhs-insects
globalbioticinteractions/vectorbase
globalbioticinteractions/vertnet
globalbioticinteractions/scan

**Comment by jhpoelen** [comment]
Error was reproduced in travis - https://travis-ci.com/github/globalbioticinteractions/ucsb-izc .

Looks like files README.md and globi.json were (accidentally?) removed via https://github.com/globalbioticinteractions/ucsb-izc/commit/665832f992dc1add33d31fb78e1266b580014d19 .

**Comment by seltmann** [comment]
That was it, thanks
